config:
  thread_db_building: 4
benchmarks:
  - algorithm: HS256
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000
  - algorithm: HS384
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000
  - algorithm: HS512
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000
  - algorithm: RS256
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000
  - algorithm: RS384
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000
  - algorithm: RS512
    tests:
      - active: true
        thread_number: 1
      - active: true
        thread_number: 2
      - active: true
        thread_number: 3
      - active: true
        thread_number: 4
    tokens: 100000